// GENERATED by supabase/scripts/sync-shared.mjs from shared/rules.ts — DO NOT EDIT.
// Edit shared/rules.ts and run `npm run sb:sync`.
/**
 * 3xDezine — plan rules engine.
 *
 * Pure and dependency-free, like the cost engine, so the web client can check
 * every drag locally and the backend can re-check the same plan and get the
 * same answer.
 *
 * Three layers:
 *  1. Geometry that cannot be built (ERROR): degenerate or self-intersecting
 *     rooms, stub walls, openings that don't fit their wall, doors too narrow
 *     to walk through, windows taller than the wall.
 *  2. Residential minimums from the National Building Code of India 2016,
 *     Part 3 "Development Control Rules and General Building Requirements",
 *     clauses 12.2–12.4, 12.12 and 20.1 (WARNING). They are ADVISORY: the
 *     authority that approves a plan enforces its own bye-laws, which may be
 *     stricter or looser than the NBC model code.
 *  3. Advice (INFO): rooms you can't get into, daylight that meets the
 *     hot-dry minimum but not a humid climate's.
 *
 * Room types are inferred from room names (there is no room-type field), see
 * `inferRoomKind`. Rooms whose name matches nothing get only geometric rules,
 * which is what a café or an office wants.
 *
 * Conventions follow ARCHITECTURE.md: metres, XZ plane (x east, z south),
 * room polygons are closed loops without the first point repeated, opening
 * `t` is 0..1 along the wall to the opening's centre.
 */

import { estimateCost, polygonArea, wallLength } from './cost.ts';
import type {
  Catalog,
  EditCheck,
  EditLevel,
  EditPolicy,
  EditProposal,
  EditSuggestion,
  Floor,
  Opening,
  PlanEdit,
  Project,
  Room,
  RuleViolation,
  Vec2,
  Wall,
} from './types.ts';

// ---------------------------------------------------------------------------
// Policy
// ---------------------------------------------------------------------------

export const DEFAULT_POLICY: EditPolicy = { level: 'LAYOUT', lockedWallIds: [], requireReview: false };

export function effectivePolicy(project: Project): EditPolicy {
  const p = project.policy;
  return {
    level: p?.level ?? DEFAULT_POLICY.level,
    lockedWallIds: [...(p?.lockedWallIds ?? [])],
    requireReview: p?.requireReview ?? DEFAULT_POLICY.requireReview,
  };
}

const LEVEL_LABEL: Record<EditLevel, string> = {
  VIEW: 'View',
  FINISHES: 'Finishes',
  LAYOUT: 'Layout',
  FULL: 'Full',
};

// ---------------------------------------------------------------------------
// Tunables (all metres)
// ---------------------------------------------------------------------------

/** Points within this distance are the same corner — matches the plan editor's snap. */
export const CORNER_TOLERANCE_M = 0.01;
export const MIN_WALL_LENGTH_M = 0.3;
/** A door narrower than this is not a door anyone can carry a bag through. */
export const MIN_DOOR_WIDTH_M = 0.75;
/** NBC 2016 Part 3 Annex B, B-5.3.2.1: 900 mm clear opening for an accessible doorway. */
export const MIN_ENTRY_DOOR_WIDTH_M = 0.9;
/** Clear masonry kept between an opening and the end of its wall, beyond the meeting wall's half-thickness. */
export const OPENING_END_CLEARANCE_M = 0.05;

const EPS = 1e-6;

// ---------------------------------------------------------------------------
// Room types
// ---------------------------------------------------------------------------

export type RoomKind =
  | 'HABITABLE'
  | 'KITCHEN'
  | 'KITCHEN_DINING'
  | 'BATH'
  | 'WC'
  | 'BATH_WC'
  | 'CABIN'
  | 'CIRCULATION'
  | 'STORE'
  | 'OUTDOOR'
  | 'UNKNOWN';

const has = (name: string, re: RegExp) => re.test(name);

/**
 * Infers what a room is for from its name, case-insensitively. Order matters:
 * "Master Toilet" is a toilet, not a bedroom; "Living Hall" is a living room,
 * while a bare "Hall" or "Entry Hall" is circulation.
 */
export function inferRoomKind(name: string): RoomKind {
  const n = ` ${name.toLowerCase().replace(/[^a-z0-9.]+/g, ' ')} `;
  if (has(n, /\b(balcony|verandah|veranda|terrace|deck|sit ?out|patio|courtyard|garden|porch)\b/)) return 'OUTDOOR';
  if (has(n, /kitchen/)) return has(n, /\b(dining|dine|diner)\b/) ? 'KITCHEN_DINING' : 'KITCHEN';
  const bath = has(n, /\b(bath|shower)\b/);
  const wc = has(n, /\b(wc|w\.c\.?|water closet|powder|lavatory|loo)\b/);
  if (has(n, /\b(toilet|bathroom|washroom|ensuite|en suite)\b/) || (bath && wc)) return 'BATH_WC';
  if (wc) return 'WC';
  if (bath) return 'BATH';
  if (has(n, /\bcabin\b/)) return 'CABIN';
  if (has(n, /\b(store|storage|utility|laundry|wash|pooja|puja|prayer|dress|dressing|wardrobe|closet|pantry|shaft|duct|garage|parking)\b/)) return 'STORE';
  if (has(n, /\b(bed|bedroom|master|guest|kids?|child|children|nursery|living|lounge|drawing|family|dining|study|den|library)\b/)) return 'HABITABLE';
  if (has(n, /\b(hall|hallway|corridor|passage|entry|entrance|foyer|lobby|vestibule|landing|stair|stairs|staircase)\b/)) return 'CIRCULATION';
  return 'UNKNOWN';
}

const isToiletKind = (k: RoomKind) => k === 'BATH' || k === 'WC' || k === 'BATH_WC';
const isKitchenKind = (k: RoomKind) => k === 'KITCHEN' || k === 'KITCHEN_DINING';

const NBC = 'NBC 2016 Part 3';
const ADVISORY = 'Advisory — your local bye-laws may differ.';

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

const sub = (a: Vec2, b: Vec2): Vec2 => ({ x: a.x - b.x, z: a.z - b.z });
const add = (a: Vec2, b: Vec2): Vec2 => ({ x: a.x + b.x, z: a.z + b.z });
const scale = (a: Vec2, s: number): Vec2 => ({ x: a.x * s, z: a.z * s });
const dot = (a: Vec2, b: Vec2) => a.x * b.x + a.z * b.z;
const cross = (a: Vec2, b: Vec2) => a.x * b.z - a.z * b.x;
const len = (a: Vec2) => Math.hypot(a.x, a.z);
const near = (a: Vec2, b: Vec2, tol = CORNER_TOLERANCE_M) =>
  Math.abs(a.x - b.x) <= tol + EPS && Math.abs(a.z - b.z) <= tol + EPS;
const lerp = (a: Vec2, b: Vec2, s: number): Vec2 => ({ x: a.x + (b.x - a.x) * s, z: a.z + (b.z - a.z) * s });

function signedArea(poly: Vec2[]): number {
  let s = 0;
  for (let i = 0; i < poly.length; i++) {
    const a = poly[i];
    const b = poly[(i + 1) % poly.length];
    s += a.x * b.z - b.x * a.z;
  }
  return s / 2;
}

function distToSegment(p: Vec2, a: Vec2, b: Vec2): number {
  const ab = sub(b, a);
  const l2 = dot(ab, ab);
  if (l2 < EPS) return len(sub(p, a));
  const t = Math.max(0, Math.min(1, dot(sub(p, a), ab) / l2));
  return len(sub(p, add(a, scale(ab, t))));
}

function orient(a: Vec2, b: Vec2, c: Vec2): number {
  const v = cross(sub(b, a), sub(c, a));
  return Math.abs(v) < 1e-9 ? 0 : Math.sign(v);
}

function onSeg(a: Vec2, b: Vec2, p: Vec2): boolean {
  return (
    Math.min(a.x, b.x) - 1e-9 <= p.x && p.x <= Math.max(a.x, b.x) + 1e-9 &&
    Math.min(a.z, b.z) - 1e-9 <= p.z && p.z <= Math.max(a.z, b.z) + 1e-9
  );
}

function segmentsIntersect(p1: Vec2, p2: Vec2, q1: Vec2, q2: Vec2): boolean {
  const o1 = orient(p1, p2, q1);
  const o2 = orient(p1, p2, q2);
  const o3 = orient(q1, q2, p1);
  const o4 = orient(q1, q2, p2);
  if (o1 !== o2 && o3 !== o4) return true;
  if (o1 === 0 && onSeg(p1, p2, q1)) return true;
  if (o2 === 0 && onSeg(p1, p2, q2)) return true;
  if (o3 === 0 && onSeg(q1, q2, p1)) return true;
  if (o4 === 0 && onSeg(q1, q2, p2)) return true;
  return false;
}

export function isSelfIntersecting(poly: Vec2[]): boolean {
  const n = poly.length;
  if (n < 4) return false;
  for (let i = 0; i < n; i++) {
    const a1 = poly[i];
    const a2 = poly[(i + 1) % n];
    for (let j = i + 1; j < n; j++) {
      // Adjacent edges share a vertex by construction.
      if (j === i || (j + 1) % n === i || (i + 1) % n === j) continue;
      if (segmentsIntersect(a1, a2, poly[j], poly[(j + 1) % n])) return true;
    }
  }
  // Repeated vertices also make a loop that isn't a simple polygon.
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) if (near(poly[i], poly[j], 1e-4)) return true;
  }
  return false;
}

/**
 * The narrowest clear dimension of a room: from the middle of every edge, how
 * far you can walk straight inward before hitting another edge. For a
 * rectangle that is the short side; for an L it is the narrower arm.
 */
export function minRoomWidth(poly: Vec2[]): number {
  const n = poly.length;
  if (n < 3) return 0;
  const s = signedArea(poly) >= 0 ? 1 : -1;
  let best = Infinity;
  for (let i = 0; i < n; i++) {
    const a = poly[i];
    const b = poly[(i + 1) % n];
    const e = sub(b, a);
    const l = len(e);
    if (l < 0.05) continue;
    const d = scale(e, 1 / l);
    const normal = { x: -d.z * s, z: d.x * s };
    const origin = scale(add(a, b), 0.5);
    let hit = Infinity;
    for (let j = 0; j < n; j++) {
      if (j === i) continue;
      const p = poly[j];
      const q = poly[(j + 1) % n];
      const qp = sub(q, p);
      const denom = cross(normal, qp);
      if (Math.abs(denom) < 1e-12) continue;
      const w = sub(p, origin);
      const t = cross(w, qp) / denom;
      const u = cross(w, normal) / denom;
      if (t > 1e-6 && u >= -1e-9 && u <= 1 + 1e-9) hit = Math.min(hit, t);
    }
    if (hit < best) best = hit;
  }
  return Number.isFinite(best) ? best : 0;
}

/** Length of the stretch of room edge a→b that runs along the wall's centreline band. */
function edgeOverlap(a: Vec2, b: Vec2, wall: Wall): number {
  const L = wallLength(wall.start, wall.end);
  if (L < EPS) return 0;
  const u = scale(sub(wall.end, wall.start), 1 / L);
  const tol = wall.thicknessM / 2 + 0.02;
  const da = Math.abs(cross(u, sub(a, wall.start)));
  const db = Math.abs(cross(u, sub(b, wall.start)));
  if (da > tol || db > tol) return 0;
  const ta = dot(sub(a, wall.start), u);
  const tb = dot(sub(b, wall.start), u);
  return Math.max(0, Math.min(Math.max(ta, tb), L) - Math.max(Math.min(ta, tb), 0));
}

function roomsAlongWall(floor: Floor, wall: Wall, minOverlap = 0.2): { room: Room; overlap: number }[] {
  const out: { room: Room; overlap: number }[] = [];
  for (const room of floor.rooms) {
    let overlap = 0;
    const p = room.polygon;
    for (let i = 0; i < p.length; i++) overlap += edgeOverlap(p[i], p[(i + 1) % p.length], wall);
    if (overlap >= minOverlap) out.push({ room, overlap });
  }
  return out.sort((a, b) => b.overlap - a.overlap);
}

function openingCentre(wall: Wall, o: Opening): Vec2 {
  return lerp(wall.start, wall.end, o.t);
}

/** Rooms whose boundary the opening sits on (one for a window, two for a door). */
function roomsAtOpening(floor: Floor, wall: Wall, o: Opening): Room[] {
  const c = openingCentre(wall, o);
  const L = wallLength(wall.start, wall.end);
  if (L < EPS) return [];
  const u = scale(sub(wall.end, wall.start), 1 / L);
  const tol = wall.thicknessM / 2 + 0.02;
  return floor.rooms.filter((room) => {
    const p = room.polygon;
    for (let i = 0; i < p.length; i++) {
      const a = p[i];
      const b = p[(i + 1) % p.length];
      const e = sub(b, a);
      const el = len(e);
      if (el < EPS) continue;
      if (Math.abs(cross(u, scale(e, 1 / el))) > 0.02) continue; // not parallel
      if (distToSegment(c, a, b) <= tol) return true;
    }
    return false;
  });
}

// ---------------------------------------------------------------------------
// Openings
// ---------------------------------------------------------------------------

export function isDoor(o: Opening): boolean {
  if (!o.componentId) return false;
  if (o.componentId.startsWith('door')) return true;
  return !o.componentId.startsWith('window') && o.sillM < 0.05;
}

/** Anything that lets light in above the floor: windows, and glazed or open voids with a sill. */
export function isWindow(o: Opening): boolean {
  if (isDoor(o)) return false;
  if (o.componentId?.startsWith('window')) return true;
  return o.sillM > 0.05;
}

interface Junction {
  /** Metres from the wall's start. */
  at: number;
  halfThickness: number;
  wallId: string;
}

/** Other walls that butt into this one part-way along it (T-junctions). */
function junctionsOn(floor: Floor, wall: Wall): Junction[] {
  const L = wallLength(wall.start, wall.end);
  if (L < EPS) return [];
  const u = scale(sub(wall.end, wall.start), 1 / L);
  const out: Junction[] = [];
  for (const w of floor.walls) {
    if (w.id === wall.id) continue;
    for (const p of [w.start, w.end]) {
      if (distToSegment(p, wall.start, wall.end) > CORNER_TOLERANCE_M) continue;
      const at = dot(sub(p, wall.start), u);
      if (at < CORNER_TOLERANCE_M || at > L - CORNER_TOLERANCE_M) continue;
      out.push({ at, halfThickness: w.thicknessM / 2, wallId: w.id });
    }
  }
  return out;
}

/** Clear distance needed at each end: half the thickest wall meeting there, plus a little masonry. */
function endMargins(floor: Floor, wall: Wall): [number, number] {
  const at = (p: Vec2) => {
    let half = 0;
    for (const w of floor.walls) {
      if (w.id === wall.id) continue;
      if (distToSegment(p, w.start, w.end) <= CORNER_TOLERANCE_M) half = Math.max(half, w.thicknessM / 2);
    }
    return half + OPENING_END_CLEARANCE_M;
  };
  return [at(wall.start), at(wall.end)];
}

/** [from, to] in metres along the wall. */
function openingSpan(wall: Wall, o: Opening): [number, number] {
  const c = o.t * wallLength(wall.start, wall.end);
  return [c - o.widthM / 2, c + o.widthM / 2];
}

/**
 * The centre position (metres along the wall) nearest to `desired` where an
 * opening of `width` fits: inside the end margins, clear of the wall's other
 * openings and of any wall butting into it. Undefined if there is no room.
 */
function nearestFreeCentre(
  floor: Floor,
  wall: Wall,
  openingId: string,
  width: number,
  desired: number,
): number | undefined {
  const L = wallLength(wall.start, wall.end);
  const [m0, m1] = endMargins(floor, wall);
  const pad = 0.005;
  let free: [number, number][] = [[m0 + width / 2 + pad, L - m1 - width / 2 - pad]];
  const forbidden: [number, number][] = [];
  for (const o of floor.openings) {
    if (o.wallId !== wall.id || o.id === openingId) continue;
    const [a, b] = openingSpan(wall, o);
    forbidden.push([a - width / 2 - pad, b + width / 2 + pad]);
  }
  for (const j of junctionsOn(floor, wall)) {
    forbidden.push([j.at - j.halfThickness - width / 2 - pad, j.at + j.halfThickness + width / 2 + pad]);
  }
  for (const [fa, fb] of forbidden) {
    const next: [number, number][] = [];
    for (const [a, b] of free) {
      if (fb <= a || fa >= b) next.push([a, b]);
      else {
        if (fa > a) next.push([a, fa]);
        if (fb < b) next.push([fb, b]);
      }
    }
    free = next;
  }
  let best: number | undefined;
  for (const [a, b] of free) {
    if (b < a) continue;
    const c = Math.max(a, Math.min(b, desired));
    if (best === undefined || Math.abs(c - desired) < Math.abs(best - desired)) best = c;
  }
  return best;
}

const round = (v: number, step: number) => Math.round(v / step) * step;
const fmt = (v: number, dp = 2) => (Math.round(v * 10 ** dp) / 10 ** dp).toFixed(dp);
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

// ---------------------------------------------------------------------------
// Naming things in plain language
// ---------------------------------------------------------------------------

function planCentre(floor: Floor): Vec2 {
  const pts = floor.walls.flatMap((w) => [w.start, w.end]);
  if (pts.length === 0) return { x: 0, z: 0 };
  const xs = pts.map((p) => p.x);
  const zs = pts.map((p) => p.z);
  return { x: (Math.min(...xs) + Math.max(...xs)) / 2, z: (Math.min(...zs) + Math.max(...zs)) / 2 };
}

function compassOf(floor: Floor, wall: Wall): string {
  const c = planCentre(floor);
  const mid = lerp(wall.start, wall.end, 0.5);
  const d = sub(wall.end, wall.start);
  // x is east, z is south.
  if (Math.abs(d.x) >= Math.abs(d.z)) return mid.z <= c.z ? 'north' : 'south';
  return mid.x >= c.x ? 'east' : 'west';
}

export function describeWall(floor: Floor, wall: Wall): string {
  if (wall.exterior) return `the ${compassOf(floor, wall)} exterior wall`;
  const along = roomsAlongWall(floor, wall);
  if (along.length === 0) return `interior wall ${wall.id}`;
  // Group the rooms by which side of the wall they are on.
  const u = sub(wall.end, wall.start);
  const sides: [string[], string[]] = [[], []];
  for (const { room } of along) {
    const c = room.polygon.reduce((acc, p) => add(acc, scale(p, 1 / room.polygon.length)), { x: 0, z: 0 });
    const side = cross(u, sub(c, wall.start)) >= 0 ? 0 : 1;
    if (!sides[side].includes(room.name)) sides[side].push(room.name);
  }
  const [a, b] = sides.filter((s) => s.length > 0).map((s) => s.join(' / '));
  return b ? `the wall between ${a} and ${b}` : `the ${a} wall`;
}

/** Every distinct corner on a wall: its ends, junctions part-way along it, and room vertices on it. */
function pointsOnWall(floor: Floor, wall: Wall): Vec2[] {
  const out: Vec2[] = [];
  const addPt = (p: Vec2) => {
    if (distToSegment(p, wall.start, wall.end) <= CORNER_TOLERANCE_M && !out.some((q) => near(p, q))) out.push({ ...p });
  };
  addPt(wall.start);
  addPt(wall.end);
  for (const w of floor.walls) if (w.id !== wall.id) { addPt(w.start); addPt(w.end); }
  for (const r of floor.rooms) r.polygon.forEach(addPt);
  return out;
}

export function describeOpening(floor: Floor, o: Opening): string {
  const wall = floor.walls.find((w) => w.id === o.wallId);
  const kind = isDoor(o) ? 'door' : isWindow(o) ? 'window' : 'opening';
  if (!wall) return `${kind} ${o.id}`;
  const rooms = roomsAtOpening(floor, wall, o).map((r) => r.name);
  if (kind === 'door' && wall.exterior) return rooms[0] ? `the entrance door into ${rooms[0]}` : 'the entrance door';
  if (rooms.length >= 2) return `the ${kind} between ${rooms[0]} and ${rooms[1]}`;
  if (rooms.length === 1) return `the ${rooms[0]} ${kind}`;
  return `the ${kind} in ${describeWall(floor, wall)}`;
}

// ---------------------------------------------------------------------------
// Applying edits
// ---------------------------------------------------------------------------

function findOpening(project: Project, id: string): { floor: Floor; opening: Opening } | undefined {
  for (const floor of project.floors) {
    const opening = floor.openings.find((o) => o.id === id);
    if (opening) return { floor, opening };
  }
  return undefined;
}

function findWall(project: Project, id: string): { floor: Floor; wall: Wall } | undefined {
  for (const floor of project.floors) {
    const wall = floor.walls.find((w) => w.id === id);
    if (wall) return { floor, wall };
  }
  return undefined;
}

function applyInPlace(project: Project, edit: PlanEdit): void {
  switch (edit.kind) {
    case 'MOVE_CORNER': {
      for (const floor of project.floors) {
        for (const w of floor.walls) {
          if (near(w.start, edit.from)) w.start = { x: edit.to.x, z: edit.to.z };
          if (near(w.end, edit.from)) w.end = { x: edit.to.x, z: edit.to.z };
        }
        for (const room of floor.rooms) {
          room.polygon = room.polygon.map((p) => (near(p, edit.from) ? { x: edit.to.x, z: edit.to.z } : p));
        }
      }
      return;
    }
    case 'MOVE_OPENING': {
      const hit = findOpening(project, edit.openingId);
      if (hit) hit.opening.t = Math.max(0, Math.min(1, edit.t));
      return;
    }
    case 'RESIZE_OPENING': {
      const hit = findOpening(project, edit.openingId);
      if (hit) hit.opening.widthM = edit.widthM;
      return;
    }
    case 'ADD_OPENING': {
      const host = findWall(project, edit.opening.wallId)?.floor ?? project.floors[0];
      if (host) host.openings.push(structuredClone(edit.opening));
      return;
    }
    case 'REMOVE_OPENING': {
      for (const floor of project.floors) floor.openings = floor.openings.filter((o) => o.id !== edit.openingId);
      return;
    }
  }
}

/** Applies edits in order to a deep copy. Never mutates `project` or `edits`. */
export function applyEdits(project: Project, edits: PlanEdit[]): Project {
  const next = structuredClone(project);
  for (const edit of edits) applyInPlace(next, edit);
  return next;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

interface Minimum {
  area: number;
  width: number;
  what: string;
  clause: string;
}

function minimumFor(kind: RoomKind, primary: boolean, hasStore: boolean): Minimum | undefined {
  switch (kind) {
    case 'HABITABLE':
      return primary
        ? { area: 9.5, width: 2.4, what: 'the main habitable room', clause: `${NBC}, cl. 12.2.2` }
        : { area: 7.5, width: 2.1, what: 'a second habitable room', clause: `${NBC}, cl. 12.2.2` };
    case 'KITCHEN':
      return hasStore
        ? { area: 4.5, width: 1.8, what: 'a kitchen with a separate store', clause: `${NBC}, cl. 12.3.2` }
        : { area: 5.0, width: 1.8, what: 'a kitchen', clause: `${NBC}, cl. 12.3.2` };
    case 'KITCHEN_DINING':
      return { area: 7.5, width: 2.1, what: 'a kitchen used for dining', clause: `${NBC}, cl. 12.3.2` };
    case 'BATH':
      return { area: 1.8, width: 1.2, what: 'a bathroom', clause: `${NBC}, cl. 12.4.2` };
    case 'WC':
      return { area: 1.1, width: 0.9, what: 'a water-closet', clause: `${NBC}, cl. 12.4.2` };
    case 'BATH_WC':
      return { area: 2.8, width: 1.2, what: 'a combined bath and WC', clause: `${NBC}, cl. 12.4.2` };
    case 'CABIN':
      return { area: 3.0, width: 1.0, what: 'an office cabin', clause: `${NBC}, cl. 12.12` };
    default:
      return undefined;
  }
}

function ceilingMinimum(kind: RoomKind): { height: number; clause: string } | undefined {
  if (kind === 'HABITABLE') return { height: 2.75, clause: `${NBC}, cl. 12.2.1` };
  if (isKitchenKind(kind)) return { height: 2.75, clause: `${NBC}, cl. 12.3.1` };
  if (isToiletKind(kind)) return { height: 2.1, clause: `${NBC}, cl. 12.4.1` };
  return undefined;
}

function validateFloor(floor: Floor, out: RuleViolation[], ctx: { primaryRoomId?: string; hasStore: boolean }) {
  const wallsById = new Map(floor.walls.map((w) => [w.id, w]));

  // --- Walls ---------------------------------------------------------------
  for (const wall of floor.walls) {
    const L = wallLength(wall.start, wall.end);
    if (L < MIN_WALL_LENGTH_M - EPS) {
      out.push({
        ruleId: 'wall.min-length',
        severity: 'ERROR',
        message: `${cap(describeWall(floor, wall))} is ${fmt(L)} m long; a wall needs at least ${MIN_WALL_LENGTH_M} m to be built. Merge it into its neighbour or pull the corners apart.`,
        wallId: wall.id,
      });
    }
  }

  // --- Openings ------------------------------------------------------------
  const byWall = new Map<string, Opening[]>();
  for (const o of floor.openings) {
    const wall = wallsById.get(o.wallId);
    if (!wall) {
      out.push({
        ruleId: 'opening.wall-missing',
        severity: 'ERROR',
        message: `Opening ${o.id} refers to wall ${o.wallId}, which doesn't exist.`,
        openingId: o.id,
      });
      continue;
    }
    const list = byWall.get(wall.id) ?? [];
    list.push(o);
    byWall.set(wall.id, list);

    const name = describeOpening(floor, o);
    const L = wallLength(wall.start, wall.end);
    const [m0, m1] = endMargins(floor, wall);
    const [a, b] = openingSpan(wall, o);
    if (a < m0 - 1e-4 || b > L - m1 + 1e-4) {
      out.push({
        ruleId: 'opening.outside-wall',
        severity: 'ERROR',
        message:
          o.widthM > L - m0 - m1
            ? `${cap(name)} is ${fmt(o.widthM)} m wide but ${describeWall(floor, wall)} only has ${fmt(Math.max(0, L - m0 - m1))} m of clear length.`
            : `${cap(name)} runs past the end of ${describeWall(floor, wall)}; it needs ${fmt(Math.max(m0, m1))} m of solid wall at the corner.`,
        wallId: wall.id,
        openingId: o.id,
      });
    }
    for (const j of junctionsOn(floor, wall)) {
      if (a < j.at + j.halfThickness - 1e-4 && b > j.at - j.halfThickness + 1e-4) {
        const other = wallsById.get(j.wallId);
        out.push({
          ruleId: 'opening.at-junction',
          severity: 'ERROR',
          message: `${cap(name)} runs into ${other ? describeWall(floor, other) : `wall ${j.wallId}`}, which meets ${describeWall(floor, wall)} at that point.`,
          wallId: wall.id,
          openingId: o.id,
        });
        break;
      }
    }
    if (o.sillM + o.heightM > wall.heightM + 1e-6) {
      out.push({
        ruleId: 'opening.too-tall',
        severity: 'ERROR',
        message: `${cap(name)} reaches ${fmt(o.sillM + o.heightM)} m (sill ${fmt(o.sillM)} m + ${fmt(o.heightM)} m) but the wall is only ${fmt(wall.heightM)} m high.`,
        wallId: wall.id,
        openingId: o.id,
      });
    }
    if (isDoor(o)) {
      if (o.widthM < MIN_DOOR_WIDTH_M - 1e-6) {
        out.push({
          ruleId: 'door.min-width',
          severity: 'ERROR',
          message: `${cap(name)} is ${fmt(o.widthM)} m wide; ${MIN_DOOR_WIDTH_M} m is the narrowest usable door.`,
          wallId: wall.id,
          openingId: o.id,
        });
      } else if (wall.exterior && o.widthM < MIN_ENTRY_DOOR_WIDTH_M - 1e-6) {
        out.push({
          ruleId: 'door.entry-width',
          severity: 'WARNING',
          message: `${cap(name)} is ${fmt(o.widthM)} m wide. A main entrance should give at least ${MIN_ENTRY_DOOR_WIDTH_M} m clear so a wheelchair, a pram or furniture can get in. ${ADVISORY}`,
          reference: `${NBC}, Annex B, B-5.3.2.1`,
          wallId: wall.id,
          openingId: o.id,
        });
      }
    }
  }

  for (const [wallId, list] of byWall) {
    const wall = wallsById.get(wallId)!;
    const spans = list.map((o) => ({ o, span: openingSpan(wall, o) })).sort((p, q) => p.span[0] - q.span[0]);
    for (let i = 0; i < spans.length; i++) {
      for (let j = i + 1; j < spans.length; j++) {
        if (spans[j].span[0] >= spans[i].span[1] - 1e-4) break;
        // Reported against both, so whichever one the user just moved carries it.
        for (const [a, b] of [[spans[j].o, spans[i].o], [spans[i].o, spans[j].o]]) {
          out.push({
            ruleId: 'opening.overlap',
            severity: 'ERROR',
            message: (() => {
              const an = describeOpening(floor, a);
              const bn = describeOpening(floor, b);
              return an === bn
                ? `${cap(an)} (${a.id}) overlaps another one (${b.id}) on ${describeWall(floor, wall)}.`
                : `${cap(an)} overlaps ${bn} on ${describeWall(floor, wall)}.`;
            })(),
            wallId,
            openingId: a.id,
          });
        }
      }
    }
  }

  // --- Rooms ---------------------------------------------------------------
  for (const room of floor.rooms) {
    const area = polygonArea(room.polygon);
    if (room.polygon.length < 3 || area < 0.01) {
      out.push({
        ruleId: 'room.degenerate',
        severity: 'ERROR',
        message: `${room.name} has no floor area — its corners have collapsed onto a line.`,
        roomId: room.id,
      });
      continue;
    }
    if (isSelfIntersecting(room.polygon)) {
      out.push({
        ruleId: 'room.self-intersecting',
        severity: 'ERROR',
        message: `${room.name}'s outline crosses itself, so it has no single floor. Move the corner back so the walls don't cross.`,
        roomId: room.id,
      });
      continue;
    }

    const kind = inferRoomKind(room.name);
    const width = minRoomWidth(room.polygon);
    const min = minimumFor(kind, room.id === ctx.primaryRoomId, ctx.hasStore);
    if (min) {
      if (area < min.area - 1e-6) {
        out.push({
          ruleId: 'room.min-area',
          severity: 'WARNING',
          message: `${room.name} is ${fmt(area)} m², below the ${min.area} m² NBC minimum for ${min.what}. ${ADVISORY}`,
          reference: min.clause,
          roomId: room.id,
        });
      }
      if (width < min.width - 1e-6) {
        out.push({
          ruleId: 'room.min-width',
          severity: 'WARNING',
          message: `${room.name} is only ${fmt(width)} m wide at its narrowest; the NBC asks for at least ${min.width} m for ${min.what}. ${ADVISORY}`,
          reference: min.clause,
          roomId: room.id,
        });
      }
    }

    const ceiling = ceilingMinimum(kind);
    if (ceiling && room.ceilingHeightM < ceiling.height - 1e-6) {
      out.push({
        ruleId: 'room.ceiling-height',
        severity: 'WARNING',
        message:
          `${room.name}'s ceiling is ${fmt(room.ceilingHeightM)} m, below the ${ceiling.height} m NBC minimum.` +
          (kind === 'HABITABLE' ? ' An air-conditioned room may go down to 2.4 m under a false ceiling.' : '') +
          ` ${ADVISORY}`,
        reference: ceiling.clause,
        roomId: room.id,
      });
    }

    // Openings on this room's boundary.
    const mine: { o: Opening; wall: Wall }[] = [];
    for (const o of floor.openings) {
      const wall = wallsById.get(o.wallId);
      if (wall && roomsAtOpening(floor, wall, o).some((r) => r.id === room.id)) mine.push({ o, wall });
    }

    // Daylight: NBC 20.1.2 — openings to the outside, excluding doors.
    if (kind === 'HABITABLE' || isKitchenKind(kind)) {
      const k = isKitchenKind(kind) ? 1.25 : 1;
      const glazing = mine
        .filter(({ o, wall }) => wall.exterior && isWindow(o))
        .reduce((s, { o }) => s + o.widthM * o.heightM, 0);
      const need = (area / 10) * k;
      const humid = (area / 6) * k;
      const kitchenNote = k > 1 ? ' (kitchens need 25% more)' : '';
      if (glazing < need - 1e-6) {
        out.push({
          ruleId: 'room.daylight',
          severity: 'WARNING',
          message: `${room.name} has ${fmt(glazing)} m² of window to the outside for ${fmt(area)} m² of floor; the NBC asks for at least ${fmt(need)} m² — one-tenth of the floor area${kitchenNote}, the hot-dry climate minimum. ${ADVISORY}`,
          reference: `${NBC}, cl. 20.1.2`,
          roomId: room.id,
        });
      } else if (glazing < humid - 1e-6) {
        out.push({
          ruleId: 'room.daylight-climate',
          severity: 'INFO',
          message: `${room.name}'s ${fmt(glazing)} m² of window meets the hot-dry minimum, but a warm-humid climate (most of coastal India) calls for ${fmt(humid)} m² — one-sixth of the floor${kitchenNote} — and a temperate one ${fmt((area / 8) * k)} m².`,
          reference: `${NBC}, cl. 20.1.2`,
          roomId: room.id,
        });
      }
    }

    // Bathrooms and WCs need a window or ventilator of 0.3 m², sides >= 0.3 m.
    if (isToiletKind(kind)) {
      const vented = mine.some(
        ({ o, wall }) => wall.exterior && !isDoor(o) && o.widthM >= 0.3 - EPS && o.heightM >= 0.3 - EPS && o.widthM * o.heightM >= 0.3 - EPS,
      );
      if (!vented) {
        out.push({
          ruleId: 'room.ventilation',
          severity: 'WARNING',
          message: `${room.name} has no window or ventilator to the outside of at least 0.3 m² (each side 0.3 m or more). Add one, or vent it to a shaft — shafts aren't modelled here. ${ADVISORY}`,
          reference: `${NBC}, cl. 12.4.3(f)`,
          roomId: room.id,
        });
      }
      // 12.4.4: a room containing a WC must not open directly into a kitchen.
      if (kind !== 'BATH') {
        for (const { o, wall } of mine) {
          if (isWindow(o)) continue;
          const kitchen = roomsAtOpening(floor, wall, o).find((r) => r.id !== room.id && isKitchenKind(inferRoomKind(r.name)));
          if (kitchen) {
            out.push({
              ruleId: 'room.wc-opens-into-kitchen',
              severity: 'WARNING',
              message: `${room.name} opens straight into ${kitchen.name}. The NBC doesn't allow a WC to open directly into a kitchen; reach it from a lobby or passage instead. ${ADVISORY}`,
              reference: `${NBC}, cl. 12.4.4`,
              roomId: room.id,
              openingId: o.id,
            });
          }
        }
      }
    }

    // Access: a door or opening on the boundary, or an unwalled (open-plan) edge.
    if (mine.length === 0 && floor.walls.length > 0) {
      const p = room.polygon;
      let open = false;
      for (let i = 0; i < p.length && !open; i++) {
        const a = p[i];
        const b = p[(i + 1) % p.length];
        const l = wallLength(a, b);
        if (l < 0.3) continue;
        const covered = floor.walls.reduce((s, w) => s + edgeOverlap(a, b, w), 0);
        if (covered < l - 0.3) open = true;
      }
      if (!open) {
        out.push({
          ruleId: 'room.no-access',
          severity: 'INFO',
          message: `${room.name} has no door or opening — there's no way in.`,
          roomId: room.id,
        });
      }
    }
  }
}

/** All rule violations on the plan, errors first. */
export function validatePlan(project: Project): RuleViolation[] {
  const out: RuleViolation[] = [];
  const rooms = project.floors.flatMap((f) => f.rooms);
  const habitable = rooms
    .filter((r) => inferRoomKind(r.name) === 'HABITABLE')
    .sort((a, b) => polygonArea(b.polygon) - polygonArea(a.polygon));
  const ctx = {
    primaryRoomId: habitable[0]?.id,
    hasStore: rooms.some((r) => /\b(store|storage|pantry)\b/i.test(r.name)),
  };
  for (const floor of project.floors) validateFloor(floor, out, ctx);
  const rank = { ERROR: 0, WARNING: 1, INFO: 2 } as const;
  return out.sort((a, b) => rank[a.severity] - rank[b.severity]);
}

const violationKey = (v: RuleViolation) => `${v.ruleId}|${v.roomId ?? ''}|${v.wallId ?? ''}|${v.openingId ?? ''}`;

function newViolations(before: RuleViolation[], after: RuleViolation[]): RuleViolation[] {
  const seen = new Set(before.map(violationKey));
  return after.filter((v) => !seen.has(violationKey(v)));
}

// ---------------------------------------------------------------------------
// Permissions
// ---------------------------------------------------------------------------

function isProtected(wall: Wall, policy: EditPolicy): boolean {
  return wall.exterior || policy.lockedWallIds.includes(wall.id);
}

function protectedReason(floor: Floor, wall: Wall, policy: EditPolicy): string {
  const name = cap(describeWall(floor, wall));
  if (policy.lockedWallIds.includes(wall.id)) {
    return `${name} is locked as load-bearing and can only be moved with Full access.`;
  }
  return `${name} is part of the building envelope and is locked at Layout level.`;
}

type Refusal = { reason: string; wall?: Wall; floor?: Floor; junction?: boolean };

function refusalFor(project: Project, edit: PlanEdit, policy: EditPolicy): Refusal | undefined {
  if (policy.level === 'VIEW') return { reason: 'This plan is view-only, so nothing can be changed.' };
  if (policy.level === 'FINISHES') {
    return { reason: 'At Finishes level only materials can change; walls, rooms and openings are locked.' };
  }

  if (edit.kind === 'MOVE_CORNER') {
    const exists = project.floors.some(
      (f) => f.walls.some((w) => near(w.start, edit.from) || near(w.end, edit.from)) || f.rooms.some((r) => r.polygon.some((p) => near(p, edit.from))),
    );
    if (!exists) return { reason: `There is no corner at (${fmt(edit.from.x)}, ${fmt(edit.from.z)}).` };
    if (policy.level === 'FULL') return undefined;
    const delta = sub(edit.to, edit.from);
    for (const floor of project.floors) {
      // Of the protected walls meeting at this corner, name the one the drag
      // would actually push (the one running across the drag direction).
      const atCorner = floor.walls
        .filter((w) => isProtected(w, policy) && (near(w.start, edit.from) || near(w.end, edit.from)))
        .map((w) => {
          const d = sub(w.end, w.start);
          const l = len(d) || 1;
          return { w, across: Math.abs(cross(scale(d, 1 / l), delta)) };
        })
        .sort((a, b) => b.across - a.across);
      if (atCorner.length > 0) {
        const wall = atCorner[0].w;
        return { reason: protectedReason(floor, wall, policy), wall, floor };
      }
      // A corner sitting part-way along a protected wall (a T-junction) may
      // slide along it but not leave it — that would pull the room off the envelope.
      for (const wall of floor.walls) {
        if (!isProtected(wall, policy)) continue;
        if (distToSegment(edit.from, wall.start, wall.end) <= CORNER_TOLERANCE_M &&
            distToSegment(edit.to, wall.start, wall.end) > CORNER_TOLERANCE_M) {
          return {
            reason: `This corner sits on ${describeWall(floor, wall)}, which is locked at ${LEVEL_LABEL[policy.level]} level — it can slide along that wall but not away from it.`,
            wall,
            floor,
            junction: true,
          };
        }
      }
    }
    return undefined;
  }

  // Opening edits.
  let wallId: string | undefined;
  if (edit.kind === 'ADD_OPENING') {
    if (findOpening(project, edit.opening.id)) return { reason: `An opening called ${edit.opening.id} already exists.` };
    wallId = edit.opening.wallId;
  } else {
    const hit = findOpening(project, edit.openingId);
    if (!hit) return { reason: `There is no opening called ${edit.openingId}.` };
    wallId = hit.opening.wallId;
  }
  if (policy.level === 'FULL') return undefined;
  const host = findWall(project, wallId);
  if (host && policy.lockedWallIds.includes(host.wall.id)) {
    return {
      reason: `${cap(describeWall(host.floor, host.wall))} is locked as load-bearing; its doors and windows can only be changed with Full access.`,
      wall: host.wall,
      floor: host.floor,
    };
  }
  return undefined;
}

/** First refusal across a sequence of edits, each checked against the plan as left by the ones before it. */
function firstRefusal(project: Project, edits: PlanEdit[], policy: EditPolicy): { index: number; refusal: Refusal } | undefined {
  let current = project;
  for (let i = 0; i < edits.length; i++) {
    const refusal = refusalFor(current, edits[i], policy);
    if (refusal) return { index: i, refusal };
    current = applyEdits(current, [edits[i]]);
  }
  return undefined;
}

export function canEditWall(project: Project, wallId: string, policy?: EditPolicy): { allowed: boolean; reason?: string } {
  const p = policy ?? effectivePolicy(project);
  const host = findWall(project, wallId);
  if (!host) return { allowed: false, reason: `There is no wall called ${wallId}.` };
  if (p.level === 'VIEW') return { allowed: false, reason: 'This plan is view-only, so nothing can be changed.' };
  if (p.level === 'FINISHES') return { allowed: false, reason: 'At Finishes level only materials can change; walls are locked.' };
  if (p.level === 'FULL') return { allowed: true };
  if (isProtected(host.wall, p)) return { allowed: false, reason: protectedReason(host.floor, host.wall, p) };
  return { allowed: true };
}

export function canEditFinishes(project: Project, policy?: EditPolicy): { allowed: boolean; reason?: string } {
  const p = policy ?? effectivePolicy(project);
  if (p.level === 'VIEW') return { allowed: false, reason: 'This plan is view-only, so finishes can’t be changed either.' };
  return { allowed: true };
}

// ---------------------------------------------------------------------------
// checkEdit and suggestions
// ---------------------------------------------------------------------------

interface Evaluation {
  allowed: boolean;
  refusal?: { index: number; refusal: Refusal };
  violations: RuleViolation[];
}

function evaluate(project: Project, edits: PlanEdit[], policy: EditPolicy, base?: RuleViolation[]): Evaluation {
  const refusal = firstRefusal(project, edits, policy);
  if (refusal) return { allowed: false, refusal, violations: [] };
  const before = base ?? validatePlan(project);
  return { allowed: true, violations: newViolations(before, validatePlan(applyEdits(project, edits))) };
}

const SIZE_RULES = new Set(['room.min-area', 'room.min-width']);
const OPENING_FIT_RULES = new Set(['opening.outside-wall', 'opening.overlap', 'opening.at-junction']);
const blocking = (v: RuleViolation) => v.severity === 'ERROR' || SIZE_RULES.has(v.ruleId);

/** Largest s in [0, 1] with ok(s), given ok(0). Bisection: monotone enough for a single dragged corner. */
function largestFraction(ok: (s: number) => boolean, resolution: number): number {
  if (ok(1)) return 1;
  let lo = 0;
  let hi = 1;
  for (let i = 0; i < 40 && hi - lo > resolution; i++) {
    const mid = (lo + hi) / 2;
    if (ok(mid)) lo = mid;
    else hi = mid;
  }
  return lo;
}

const dirWord = (axis: 'x' | 'z', amount: number) => (axis === 'x' ? (amount > 0 ? 'east' : 'west') : amount > 0 ? 'south' : 'north');

function roomAreaIn(project: Project, roomId: string | undefined): number | undefined {
  if (!roomId) return undefined;
  for (const f of project.floors) {
    const r = f.rooms.find((x) => x.id === roomId);
    if (r) return polygonArea(r.polygon);
  }
  return undefined;
}

function roomName(project: Project, roomId: string | undefined): string | undefined {
  for (const f of project.floors) {
    const r = f.rooms.find((x) => x.id === roomId);
    if (r) return r.name;
  }
  return undefined;
}

/**
 * Moves a corner by the largest fraction of `delta` that adds no blocking
 * violation, rounded to the millimetre on the safe side.
 */
function clampMove(
  project: Project,
  prefix: PlanEdit[],
  build: (s: number, round?: boolean) => PlanEdit[],
  base: RuleViolation[],
  step: number,
): { s: number; edits: PlanEdit[] } | undefined {
  const ok = (edits: PlanEdit[]) =>
    !newViolations(base, validatePlan(applyEdits(project, [...prefix, ...edits]))).some(blocking);
  // Resolve to a fifth of the rounding step: well inside the 1 mm the result is rounded to.
  const s = largestFraction((f) => ok(build(f)), step / 5);
  if (s <= 0) return undefined;
  // Round to whole millimetres, backing off toward the start if rounding crossed the line.
  for (let k = 0; k <= 20; k++) {
    const f = Math.max(0, s - k * step);
    const edits = build(f, true);
    if (ok(edits)) return { s: f, edits };
  }
  return undefined;
}

const roundPt = (p: Vec2): Vec2 => ({ x: round(p.x, 0.001), z: round(p.z, 0.001) });

function suggestionsFor(
  project: Project,
  edits: PlanEdit[],
  policy: EditPolicy,
  base: RuleViolation[],
  outcome: Evaluation,
): EditSuggestion[] {
  const out: EditSuggestion[] = [];
  const push = (s: Omit<EditSuggestion, 'id'>) => out.push({ id: `sug-${out.length + 1}`, ...s });

  // Suggestions rework the edit that broke something, keeping the ones before it.
  const index = outcome.refusal ? outcome.refusal.index : edits.length - 1;
  if (index < 0) return out;
  const prefix = edits.slice(0, index);
  const target = edits[index];
  const atPrefix = applyEdits(project, prefix);
  const fresh = outcome.violations;

  // --- Refused: offer the nearest permitted alternative ---------------------
  if (outcome.refusal) {
    const { refusal } = outcome.refusal;
    if (target.kind !== 'MOVE_CORNER' || !refusal.wall || !refusal.floor) return out;
    const floor = refusal.floor;
    const wall = refusal.wall;
    const delta = sub(target.to, target.from);
    if (len(delta) < CORNER_TOLERANCE_M) return out;

    if (refusal.junction) {
      // Slide along the protected wall instead of leaving it.
      const L = wallLength(wall.start, wall.end);
      const u = scale(sub(wall.end, wall.start), 1 / L);
      const along = dot(delta, u);
      const at = Math.max(0, Math.min(L, dot(sub(target.from, wall.start), u) + along));
      const to = roundPt(add(wall.start, scale(u, at)));
      if (len(sub(to, target.from)) >= CORNER_TOLERANCE_M) {
        push({
          title: `Slide along ${describeWall(floor, wall)}`,
          rationale: `${cap(describeWall(floor, wall))} can't move at ${LEVEL_LABEL[policy.level]} level, but the corner can slide ${fmt(len(sub(to, target.from)))} m along it, which keeps the room attached to the wall.`,
          edits: [...prefix, { kind: 'MOVE_CORNER', from: target.from, to }],
          resolves: [],
        });
      }
      return verify(project, out, policy, base);
    }

    // Move the room's opposite interior wall the other way, so the room
    // changes size by the same amount without the locked wall moving.
    const axis: 'x' | 'z' = Math.abs(delta.x) >= Math.abs(delta.z) ? 'x' : 'z';
    const amount = delta[axis];
    if (Math.abs(amount) < 0.05) return out;
    const rooms = floor.rooms.filter((r) => r.polygon.some((p) => near(p, target.from)));
    const tried = new Set<string>();
    for (const room of rooms) {
      for (const w of floor.walls) {
        if (tried.has(w.id) || isProtected(w, policy)) continue;
        if (Math.abs(w.start[axis] - w.end[axis]) > CORNER_TOLERANCE_M) continue; // must run across the move
        if (Math.abs(w.start[axis] - target.from[axis]) < 0.05) continue; // same side as the locked wall
        const along = roomsAlongWall(floor, w, 0.3).some((x) => x.room.id === room.id);
        if (!along) continue;
        tried.add(w.id);
        // Move the whole wall: its ends plus every junction and room vertex
        // along it, so walls that butt into it stay attached.
        const points = pointsOnWall(floor, w);
        const shift = (s: number, r = false): PlanEdit[] => {
          const d: Vec2 = axis === 'x' ? { x: -amount * s, z: 0 } : { x: 0, z: -amount * s };
          return points.map((p) => ({ kind: 'MOVE_CORNER', from: { ...p }, to: r ? roundPt(add(p, d)) : add(p, d) }));
        };
        const fit = clampMove(project, prefix, shift, base, 0.001 / Math.abs(amount));
        if (!fit || fit.s * Math.abs(amount) < 0.05) continue;
        const dist = fit.s * Math.abs(amount);
        const name = describeWall(floor, w);
        const before = polygonArea(room.polygon);
        const moved = applyEdits(atPrefix, fit.edits);
        const afterArea = roomAreaIn(moved, room.id) ?? before;
        const others = floor.rooms
          .filter((r) => r.id !== room.id && Math.abs((roomAreaIn(moved, r.id) ?? 0) - polygonArea(r.polygon)) > 0.01)
          .map((r) => r.name);
        push({
          title: `Move ${name} instead`,
          rationale:
            `${refusal.reason} Moving ${name} ${fmt(dist)} m ${dirWord(axis, -amount)} changes ${room.name} from ${fmt(before)} m² to ${fmt(afterArea)} m² without moving ${describeWall(floor, wall)}` +
            (others.length ? ` (${others.join(', ')} ${others.length === 1 ? 'changes' : 'change'} too)` : '') +
            (fit.s < 1 ? ', and stops where a neighbouring room would drop below its minimum size.' : '.'),
          edits: [...prefix, ...fit.edits],
          resolves: [],
        });
      }
    }
    return verify(project, out, policy, base);
  }

  if (fresh.length === 0) return out;

  // --- A corner move broke a size rule or the geometry: clamp it -------------
  if (target.kind === 'MOVE_CORNER') {
    const delta = sub(target.to, target.from);
    const dist = len(delta);
    const breaks = fresh.filter(blocking);
    if (breaks.length > 0 && dist >= CORNER_TOLERANCE_M) {
      const build = (s: number, r = false): PlanEdit[] => {
        const to = lerp(target.from, target.to, s);
        return [{ kind: 'MOVE_CORNER', from: target.from, to: r ? roundPt(to) : to }];
      };
      const fit = clampMove(project, prefix, build, base, 0.001 / dist);
      if (fit && fit.s * dist >= CORNER_TOLERANCE_M) {
        const moved = fit.s * dist;
        const lead = breaks.find((v) => SIZE_RULES.has(v.ruleId)) ?? breaks[0];
        // What actually stops the corner: the first blocking rule just past the clamp point.
        const past = Math.min(1, fit.s + (2 * CORNER_TOLERANCE_M) / dist);
        const binding =
          newViolations(base, validatePlan(applyEdits(project, [...prefix, ...build(past)]))).filter(blocking)
            .sort((a, b) => Number(SIZE_RULES.has(b.ruleId)) - Number(SIZE_RULES.has(a.ruleId)))[0] ?? lead;
        const clampedPlan = applyEdits(project, [...prefix, ...fit.edits]);
        const name = roomName(project, binding.roomId);
        let keeps = 'keeps every wall and opening buildable';
        if (binding.ruleId === 'room.min-area' && name) keeps = `keeps ${name} at ${fmt(roomAreaIn(clampedPlan, binding.roomId) ?? 0)} m²`;
        else if (binding.ruleId === 'room.min-width' && name) {
          const r = clampedPlan.floors.flatMap((f) => f.rooms).find((x) => x.id === binding.roomId);
          keeps = `keeps ${name} ${fmt(r ? minRoomWidth(r.polygon) : 0)} m wide`;
        }
        const plain = (v: RuleViolation) => v.message.replace(` ${ADVISORY}`, '');
        push({
          title: `Stop the wall after ${fmt(moved)} m — ${keeps}`,
          rationale:
            `The full ${fmt(dist)} m move breaks a rule: ${plain(lead)} Stopping after ${fmt(moved)} m is as far as the corner can go` +
            (binding === lead
              ? ' while every affected room stays at or above its minimum.'
              : ` without breaking anything else — any further and: ${plain(binding)}`),
          edits: [...prefix, ...fit.edits],
          resolves: [...new Set(breaks.map((v) => v.ruleId))],
        });
      }
    }

    // The move only pushed openings off their (now shorter) walls: shift them.
    const fitBreaks = fresh.filter((v) => OPENING_FIT_RULES.has(v.ruleId) && v.openingId);
    if (fitBreaks.length > 0 && !fresh.some((v) => blocking(v) && !OPENING_FIT_RULES.has(v.ruleId))) {
      const after = applyEdits(project, [...prefix, target]);
      const extra: PlanEdit[] = [];
      let working = after;
      for (const id of [...new Set(fitBreaks.map((v) => v.openingId!))]) {
        const hit = findOpening(working, id);
        const host = hit && hit.floor.walls.find((w) => w.id === hit.opening.wallId);
        if (!hit || !host) continue;
        const L = wallLength(host.start, host.end);
        const c = nearestFreeCentre(hit.floor, host, id, hit.opening.widthM, hit.opening.t * L);
        if (c === undefined) continue;
        const move: PlanEdit = { kind: 'MOVE_OPENING', openingId: id, t: round(c / L, 0.0001) };
        extra.push(move);
        working = applyEdits(working, [move]);
      }
      if (extra.length > 0) {
        push({
          title: extra.length === 1 ? 'Move the corner and shift the opening to fit' : 'Move the corner and shift the openings to fit',
          rationale: `Moving the corner shortens a wall so ${fitBreaks.length === 1 ? 'an opening no longer fits' : 'some openings no longer fit'}. Sliding ${extra.length === 1 ? 'it' : 'them'} along the wall keeps the move and keeps every opening buildable.`,
          edits: [...prefix, target, ...extra],
          resolves: [...new Set(fitBreaks.map((v) => v.ruleId))],
        });
      }
    }
    return verify(project, out, policy, base);
  }

  // --- Opening edits --------------------------------------------------------
  const openingId = target.kind === 'ADD_OPENING' ? target.opening.id : target.openingId;
  const after = applyEdits(project, [...prefix, target]);
  const hit = findOpening(after, openingId);
  if (!hit) return out;
  const { floor, opening } = hit;
  const wall = floor.walls.find((w) => w.id === opening.wallId);
  if (!wall) return out;
  const L = wallLength(wall.start, wall.end);
  const mineFresh = fresh.filter((v) => v.openingId === openingId);
  const name = describeOpening(floor, opening);

  /** Edits that put this opening at `width`/`t` (and sill), expressed in the same kind as the user's edit. */
  const rewrite = (width: number, t: number, sill = opening.sillM): PlanEdit[] => {
    if (target.kind === 'ADD_OPENING') return [{ kind: 'ADD_OPENING', opening: { ...target.opening, widthM: width, t, sillM: sill } }];
    const list: PlanEdit[] = [];
    if (target.kind === 'RESIZE_OPENING' || width !== opening.widthM) list.push({ kind: 'RESIZE_OPENING', openingId, widthM: width });
    if (target.kind === 'MOVE_OPENING' || Math.abs(t - opening.t) > 1e-9) list.push({ kind: 'MOVE_OPENING', openingId, t });
    return list;
  };
  /** Keeps `t` if the opening fits there at `width`, else the nearest spot where it does. */
  const placeFor = (width: number): number | undefined => {
    const [m0, m1] = endMargins(floor, wall);
    const c = opening.t * L;
    const clear =
      c - width / 2 >= m0 - 1e-4 &&
      c + width / 2 <= L - m1 + 1e-4 &&
      !floor.openings.some((o) => {
        if (o.wallId !== wall.id || o.id === openingId) return false;
        const [a, b] = openingSpan(wall, o);
        return a < c + width / 2 - 1e-4 && b > c - width / 2 + 1e-4;
      }) &&
      !junctionsOn(floor, wall).some((j) => c - width / 2 < j.at + j.halfThickness - 1e-4 && c + width / 2 > j.at - j.halfThickness + 1e-4);
    if (clear) return opening.t;
    const free = nearestFreeCentre(floor, wall, openingId, width, c);
    return free === undefined ? undefined : round(free / L, 0.0001);
  };

  // Door too narrow: snap up to the minimum.
  const narrow = mineFresh.find((v) => v.ruleId === 'door.min-width' || v.ruleId === 'door.entry-width');
  if (narrow && (target.kind === 'RESIZE_OPENING' || target.kind === 'ADD_OPENING')) {
    const width = wall.exterior ? MIN_ENTRY_DOOR_WIDTH_M : MIN_DOOR_WIDTH_M;
    const t = placeFor(width);
    if (t !== undefined) {
      push({
        title: `Make the door ${fmt(width)} m wide`,
        rationale:
          (wall.exterior
            ? `An entrance door needs at least ${fmt(width)} m clear so a wheelchair or furniture can get through.`
            : `${fmt(width)} m is the narrowest door that's practical to walk through.`) +
          (t !== opening.t ? ' It is shifted slightly so it still fits the wall.' : ''),
        edits: [...prefix, ...rewrite(width, t)],
        resolves: [narrow.ruleId],
      });
    }
  }

  // Off the wall, over another opening, or into a junction: move it to the nearest clear spot.
  const misplaced = mineFresh.filter((v) => OPENING_FIT_RULES.has(v.ruleId));
  if (misplaced.length > 0) {
    const c = nearestFreeCentre(floor, wall, openingId, opening.widthM, opening.t * L);
    if (c !== undefined) {
      const t = round(c / L, 0.0001);
      push({
        title: `Move ${name} ${fmt(Math.abs(c - opening.t * L))} m along the wall`,
        rationale: `That is the nearest position where ${name} sits fully inside ${describeWall(floor, wall)}, clear of the corners, the other openings and any wall that meets it.`,
        edits: [...prefix, ...rewrite(opening.widthM, t)],
        resolves: [...new Set(misplaced.map((v) => v.ruleId))],
      });
    }
    // A resize that no longer fits: offer the widest size that fits where it is.
    if (target.kind === 'RESIZE_OPENING') {
      const original = findOpening(atPrefix, openingId)?.opening;
      const cen = opening.t * L;
      const free = nearestFreeCentre(floor, wall, openingId, 0, cen);
      if (original && free !== undefined && Math.abs(free - cen) < 1e-3) {
        // Grow from the original width until it stops fitting.
        const minW = isDoor(opening) ? (wall.exterior ? MIN_ENTRY_DOOR_WIDTH_M : MIN_DOOR_WIDTH_M) : 0.3;
        let lo = Math.max(minW, 0);
        let hi = opening.widthM;
        const fits = (w: number) => {
          const at = nearestFreeCentre(floor, wall, openingId, w, cen);
          return at !== undefined && Math.abs(at - cen) < 1e-6;
        };
        if (fits(lo)) {
          for (let i = 0; i < 30; i++) {
            const mid = (lo + hi) / 2;
            if (fits(mid)) lo = mid;
            else hi = mid;
          }
          const width = Math.floor(lo * 100) / 100;
          if (width > original.widthM + 0.005 && width >= minW) {
            push({
              title: `Make it ${fmt(width)} m wide instead`,
              rationale: `${fmt(width)} m is the widest ${name} can be at its current position on ${describeWall(floor, wall)}.`,
              edits: [...prefix, { kind: 'RESIZE_OPENING', openingId, widthM: width }],
              resolves: [...new Set(misplaced.map((v) => v.ruleId))],
            });
          }
        }
      }
    }
  }

  // A new window taller than its wall: lower the sill.
  const tall = mineFresh.find((v) => v.ruleId === 'opening.too-tall');
  if (tall && target.kind === 'ADD_OPENING') {
    const sill = Math.floor((wall.heightM - opening.heightM) * 100 + 1e-9) / 100;
    if (sill >= 0) {
      push({
        title: `Lower the sill to ${fmt(sill)} m`,
        rationale: `With a ${fmt(sill)} m sill the ${fmt(opening.heightM)} m-high opening fits under the ${fmt(wall.heightM)} m wall.`,
        edits: [...prefix, ...rewrite(opening.widthM, opening.t, sill)],
        resolves: ['opening.too-tall'],
      });
    }
  }

  return verify(project, out, policy, base);
}

/** Drops any suggestion that would itself be refused or add an ERROR, and duplicates. */
function verify(project: Project, list: EditSuggestion[], policy: EditPolicy, base: RuleViolation[]): EditSuggestion[] {
  const seen = new Set<string>();
  const kept: EditSuggestion[] = [];
  for (const s of list) {
    const key = JSON.stringify(s.edits);
    if (seen.has(key)) continue;
    seen.add(key);
    const e = evaluate(project, s.edits, policy, base);
    if (!e.allowed || e.violations.some((v) => v.severity === 'ERROR')) continue;
    kept.push({ ...s, id: `sug-${kept.length + 1}` });
  }
  return kept;
}

/**
 * Would these edits be allowed under `policy`, and what would they break?
 * `violations` lists only what is NEW after the edits — a plan that already
 * had a low ceiling doesn't re-report it on every drag.
 */
export function checkEdit(project: Project, edits: PlanEdit[], policy?: EditPolicy): EditCheck {
  const p = policy ?? effectivePolicy(project);
  const base = validatePlan(project);
  const outcome = evaluate(project, edits, p, base);
  const suggestions = edits.length > 0 ? suggestionsFor(project, edits, p, base, outcome) : [];
  if (!outcome.allowed) {
    return { allowed: false, reason: outcome.refusal!.refusal.reason, violations: [], suggestions };
  }
  return { allowed: true, violations: outcome.violations, suggestions };
}

// ---------------------------------------------------------------------------
// Proposals
// ---------------------------------------------------------------------------

let proposalSeq = 0;

function proposalId(): string {
  proposalSeq = (proposalSeq + 1) % 1296;
  return `prop-${Date.now().toString(36)}${proposalSeq.toString(36).padStart(2, '0')}${Math.floor(Math.random() * 1296).toString(36).padStart(2, '0')}`;
}

/**
 * Packages edits for review. The caller appends it to `project.proposals`;
 * this function doesn't change the project.
 */
export function createProposal(
  project: Project,
  edits: PlanEdit[],
  author: string,
  catalog: Catalog,
  note?: string,
): EditProposal {
  const proposed = applyEdits(project, edits);
  const before = estimateCost(project, catalog).total;
  const after = estimateCost(proposed, catalog).total;
  return {
    id: proposalId(),
    author,
    createdAt: new Date().toISOString(),
    ...(note ? { note } : {}),
    edits: structuredClone(edits),
    status: 'PENDING',
    violations: validatePlan(proposed),
    costDelta: Math.round((after - before) * 100) / 100,
  };
}

function decide(project: Project, proposalId: string, status: 'ACCEPTED' | 'REJECTED'): Project {
  const proposal = project.proposals?.find((p) => p.id === proposalId);
  if (!proposal) throw new Error(`No proposal with id "${proposalId}".`);
  if (proposal.status !== 'PENDING') throw new Error(`Proposal "${proposalId}" was already ${proposal.status.toLowerCase()}.`);
  const next = status === 'ACCEPTED' ? applyEdits(project, proposal.edits) : structuredClone(project);
  const violations = status === 'ACCEPTED' ? validatePlan(next) : undefined;
  next.proposals = next.proposals!.map((p) =>
    p.id === proposalId ? { ...p, status, ...(violations ? { violations } : {}) } : p,
  );
  return next;
}

/** Applies a pending proposal's edits, marks it ACCEPTED and refreshes its violations against the result. Throws if it isn't pending. */
export function acceptProposal(project: Project, proposalId: string): Project {
  return decide(project, proposalId, 'ACCEPTED');
}

/** Marks a pending proposal REJECTED; the plan is unchanged. Throws if it isn't pending. */
export function rejectProposal(project: Project, proposalId: string): Project {
  return decide(project, proposalId, 'REJECTED');
}
