#!/usr/bin/env node
/**
 * Copies the shared domain code the Edge Functions run — the rules engine, the
 * cost engine, the types and the catalog — from `shared/` into
 * `supabase/functions/_shared/domain/`, so the functions execute exactly the
 * same logic as the web editor instead of a fork.
 *
 * Why a copy and not an import map pointing at ../../shared: `shared/` uses
 * NodeNext-style specifiers (`./types.js` for a .ts file), which Deno does not
 * resolve, and `supabase functions deploy` only reliably bundles files under
 * `supabase/functions/`. The copy rewrites relative `./x.js` specifiers to
 * `./x.ts` and changes nothing else; the catalog JSON is wrapped as a .ts
 * module (`domain/catalog.ts`).
 *
 *   node supabase/scripts/sync-shared.mjs          write the copies
 *   node supabase/scripts/sync-shared.mjs --check  exit 1 if they have drifted
 *
 * The copies are committed (deploys need them); `npm run sb:functions`,
 * `sb:test` and `sb:e2e` run the check / sync first.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const from = join(root, 'shared');
const to = join(root, 'supabase/functions/_shared/domain');
// [source in shared/, target in _shared/domain/]. The catalog becomes a .ts
// module so no bundler has to support JSON import attributes.
const FILES = [
  ['types.ts', 'types.ts'],
  ['cost.ts', 'cost.ts'],
  ['rules.ts', 'rules.ts'],
  ['cloud.ts', 'cloud.ts'],
  ['catalog.seed.json', 'catalog.ts'],
];

const HEADER =
  '// GENERATED by supabase/scripts/sync-shared.mjs from shared/{file} — DO NOT EDIT.\n' +
  '// Edit shared/{file} and run `npm run sb:sync`.\n';

function render(file) {
  const src = readFileSync(join(from, file), 'utf8');
  if (file.endsWith('.json')) {
    return (
      HEADER.replaceAll('{file}', file) +
      "import type { Catalog } from './types.ts';\n\n" +
      `const catalog = ${JSON.stringify(JSON.parse(src), null, 2)} as unknown as Catalog;\n\nexport default catalog;\n`
    );
  }
  const body = src.replace(/(from\s+['"])(\.\.?\/[^'"]+?)\.js(['"])/g, '$1$2.ts$3');
  return HEADER.replaceAll('{file}', file) + body;
}

const check = process.argv.includes('--check');
const drift = [];
if (!check) mkdirSync(to, { recursive: true });
for (const [file, target] of FILES) {
  const want = render(file);
  const path = join(to, target);
  const have = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (have === want) continue;
  if (check) drift.push(`shared/${file}`);
  else {
    writeFileSync(path, want);
    console.log(`synced shared/${file} -> supabase/functions/_shared/domain/${target}`);
  }
}
if (check) {
  if (drift.length) {
    console.error(`Edge Function copies of shared/ are stale: ${drift.join(', ')}. Run \`npm run sb:sync\`.`);
    process.exit(1);
  }
  console.log('supabase/functions/_shared/domain is in sync with shared/.');
}
